version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=carteiradigital;Username=postgres;Password=Mt190720@
      - Jwt__Secret=dzgwkposE/Bv3RVl3wyHkYKBGNpFdQQTPNBNa2fomHk=
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=carteiradigital
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Mt190720@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: